# bookdown for data scientists

This tutorial demonstrates how to use `bookdown`, an extension of R Markdown, to quickly create interactive data documentation for large datasets with many components and filetypes. Parts of this tutorial are adapted from the bookdown GitHub repository.

Questions for live interaction are included as callouts.

To do: focus more on what than how

## Prerequisites

All software used in this tutorial is available for free.

### Software

* [R](https://cran.rstudio.com/) (3.3.0+)
* [RStudio IDE](https://posit.co/download/rstudio-desktop/) 9
* [TeX installed in RStudio](https://bookdown.org/yihui/rmarkdown-cookbook/install-latex.html)

To publish online:

* GitHub
  * [GitHub Desktop](https://docs.github.com/en/desktop/installing-and-configuring-github-desktop/overview/getting-started-with-github-desktop) is an easy introduction to git without requiring command line

### Knowledge and experience

We assume no experience with YAML or LaTeX. Experience with GitHub, R, and R Markdown are helpful, but not necessary.
