--- 
title: "bookdown for data scientists"
#author: "Ruhan Circi, Juanita Hicks, Grant Adams, Karen Yi"
#date: "`r Sys.Date()`"
site: bookdown::bookdown_site
split_by: section
documentclass: book
classoption: openany
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
geometry: margin=3cm
df_print: kable
mainfont: Calibri Light
monofont: Consolas
urlcolor: blue
fontsize: 12pt
lang: "en"
description: "This tutorial demonstrates how to use `bookdown`, an extension of R Markdown, to quickly create interactive data documentation for large datasets with many components and filetypes. Parts of this tutorial are adapted from the bookdown GitHub repository."
---

```{r setup, echo=F, warning=F}
knitr::opts_knit$set(root.dir = "../")
```

# bookdown for data scientists

This tutorial demonstrates how to use `bookdown`, an extension of R Markdown, to quickly create interactive data documentation for large datasets with many components and filetypes. Parts of this tutorial are adapted from the bookdown GitHub repository.

Questions for live interaction are included as callouts.

To do: focus more on what than how

## Prerequisites

All software used in this tutorial is available for free.

### Software

* [R](https://cran.rstudio.com/) (3.3.0+)
* [RStudio IDE](https://posit.co/download/rstudio-desktop/) 9
* [TeX installed in RStudio](https://bookdown.org/yihui/rmarkdown-cookbook/install-latex.html)

To publish online:

* GitHub
  * [GitHub Desktop](https://docs.github.com/en/desktop/installing-and-configuring-github-desktop/overview/getting-started-with-github-desktop) is an easy introduction to git without requiring command line

### Knowledge and experience

We assume no experience with YAML or LaTeX. Experience with GitHub, R, and R Markdown are helpful, but not necessary.

